spring:
  application:
    name: order-service
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/crystal_holiday
    hikari:
      connectionTimeout: 300000   # 3 minutes

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  devtools:
    restart:
      enabled: true
    livereload:
      port: 35730
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 8200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      tinhpt:
        order:
          OrderServiceApplication: debug
